### PR TITLE
feat: add new icon gio:rocket

### PR DESCRIPTION
**Pull request by loriepisicchio**
**Issue**

Add new icon `gio:rocket`

**Description**

screenshot-localhost_9008-2023 04 18-11_31_07

---
#### 🧪&nbsp;&nbsp;Gravitee.io Automatic Prerelease @gravitee/ui-particles-angular
```
npm install @gravitee/ui-particles-angular@5.20.1-add-new-icon-7292659
```
```
yarn add @gravitee/ui-particles-angular@5.20.1-add-new-icon-7292659
```

---
#### 🧪&nbsp;&nbsp;Gravitee.io Automatic Prerelease @gravitee/ui-policy-studio-angular
```
npm install @gravitee/ui-policy-studio-angular@5.20.1-add-new-icon-7292659
```
```
yarn add @gravitee/ui-policy-studio-angular@5.20.1-add-new-icon-7292659
```

---

### CODE REVIEW

**Comment by ThibaudAV** [comment]
🤔 strange svg no ?

**Comment by loriepisicchio** [comment]
@ThibaudAV  yes and good news is: tests are failing 😁

**Comment by loriepisicchio** [comment]
@ThibaudAV all good now

**Review by ThibaudAV — APPROVED** [review]
so you also add message, compare connection, ..  icon ?

**Comment by loriepisicchio** [comment]
@ThibaudAV yes 5 more icons in the sprite file provided by Audrey

**Pull request merged**
