### PR TITLE
feat: udpate icons

### PR DESCRIPTION
**Pull request by gcusnieux**
https://graviteecommunity.atlassian.net/browse/APIM-104

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-psgugrtvfz.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.11.0-update-icons-a12d79c
# or
yarn add @gravitee/ui-particles-angular@3.11.0-update-icons-a12d79c
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.11.0-update-icons-a12d79c
# or
yarn add @gravitee/ui-policy-studio-angular@3.11.0-update-icons-a12d79c
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.11.0-update-icons-7c73a4d
# or
yarn add @gravitee/ui-particles-angular@3.11.0-update-icons-7c73a4d
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.11.0-update-icons-7c73a4d
# or
yarn add @gravitee/ui-policy-studio-angular@3.11.0-update-icons-7c73a4d
```

**Review by phiz71 — APPROVED** [review]

**Review by Okhelifi — COMMENTED** [review]
We lost the kubernetes icon I think

**Comment by gaetanmaisse** [comment]
😱 @Okhelifi is right, and it's strange that it wasn't causing Chromatic run to fail 🤔

**Comment by Okhelifi** [comment]
> 😱 @Okhelifi is right, and it's strange that it wasn't causing Chromatic run to fail 🤔

Yes and no approval needed on the story 🤔

**Review by ThibaudAV — APPROVED** [review]
haha figma link was not god now 
image

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.11.0-update-icons-8a3bc83
# or
yarn add @gravitee/ui-policy-studio-angular@3.11.0-update-icons-8a3bc83
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.11.0-update-icons-8a3bc83
# or
yarn add @gravitee/ui-particles-angular@3.11.0-update-icons-8a3bc83
```

**Review by Okhelifi — APPROVED** [review]

**Pull request merged**
