### PR TITLE
 fix: manage Plugin in license directive

### PR DESCRIPTION
**Pull request by gcusnieux**
**Issue**

https://github.com/gravitee-io/issues/issues/XXXXX

**Description**

A small description of what you did in that PR.

**Additional context**

---
#### 🧪&nbsp;&nbsp;Gravitee.io Automatic Prerelease @gravitee/ui-policy-studio-angular
```
npm install @gravitee/ui-policy-studio-angular@9.6.0-fix-license-direc-8298ebd
```
```
yarn add @gravitee/ui-policy-studio-angular@9.6.0-fix-license-direc-8298ebd
```

---
#### 🧪&nbsp;&nbsp;Gravitee.io Automatic Prerelease @gravitee/ui-particles-angular
```
npm install @gravitee/ui-particles-angular@9.6.0-fix-license-direc-8298ebd
```
```
yarn add @gravitee/ui-particles-angular@9.6.0-fix-license-direc-8298ebd
```

---

### CODE REVIEW

**Review by jourdiw — APPROVED** [review]

**Review by jourdiw — CHANGES_REQUESTED** [review]
We can add the improvement to `isExpired$` here too

**Review by jourdiw — APPROVED** [review]

**Comment by gcusnieux** [comment]
> We can add the improvement to `isExpired$` here too

No I'm really agree, it's an improvement,

**Comment by ThibaudAV** [comment]
🤞

**Pull request merged**
