### PR TITLE
feat: improve gio-form-file-picker

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**
n/a

**Description**
- allow to change the add-button size
- directly return base64 file in NewFile instance

**Additional context**

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-untizchmgl.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.13.2-file-picker-8a84544
# or
yarn add @gravitee/ui-particles-angular@3.13.2-file-picker-8a84544
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.13.2-file-picker-8a84544
# or
yarn add @gravitee/ui-policy-studio-angular@3.13.2-file-picker-8a84544
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.13.2-file-picker-f5b87d4
# or
yarn add @gravitee/ui-policy-studio-angular@3.13.2-file-picker-f5b87d4
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.13.2-file-picker-f5b87d4
# or
yarn add @gravitee/ui-particles-angular@3.13.2-file-picker-f5b87d4
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.13.2-file-picker-19ad62a
# or
yarn add @gravitee/ui-policy-studio-angular@3.13.2-file-picker-19ad62a
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.13.2-file-picker-19ad62a
# or
yarn add @gravitee/ui-particles-angular@3.13.2-file-picker-19ad62a
```

**Review by Okhelifi — APPROVED** [review]

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.13.2-file-picker-6bc384b
# or
yarn add @gravitee/ui-particles-angular@3.13.2-file-picker-6bc384b
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.13.2-file-picker-6bc384b
# or
yarn add @gravitee/ui-policy-studio-angular@3.13.2-file-picker-6bc384b
```

**Pull request merged**
