### PR TITLE
fix: angular 13.x error with color not exist in palette

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**
na
**Description**

angular 13.x error with color not exist in palette

**Additional context**
image

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-nmdzycxwhd.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@2.0.1-new-token-5e3c803
# or
yarn add @gravitee/ui-policy-studio-angular@2.0.1-new-token-5e3c803
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@2.0.1-new-token-5e3c803
# or
yarn add @gravitee/ui-particles-angular@2.0.1-new-token-5e3c803
```

**Review by jgiovaresco — APPROVED** [review]
No more error on Cockpit with this patch 🎉

**Review by gaetanmaisse — APPROVED** [review]

**Pull request merged**
