### PR TITLE
feat: update icons

### PR DESCRIPTION
**Pull request by gcusnieux**
APIM-228

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-jazbmhodtq.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.2-update-icons-db25f40
# or
yarn add @gravitee/ui-particles-angular@4.5.2-update-icons-db25f40
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.2-update-icons-db25f40
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.2-update-icons-db25f40
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.2-update-icons-5bd8d02
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.2-update-icons-5bd8d02
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.2-update-icons-5bd8d02
# or
yarn add @gravitee/ui-particles-angular@4.5.2-update-icons-5bd8d02
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.2-update-icons-dcc9385
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.2-update-icons-dcc9385
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.2-update-icons-dcc9385
# or
yarn add @gravitee/ui-particles-angular@4.5.2-update-icons-dcc9385
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.2-update-icons-4871437
# or
yarn add @gravitee/ui-particles-angular@4.5.2-update-icons-4871437
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.2-update-icons-4871437
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.2-update-icons-4871437
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.3-update-icons-c43422c
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.3-update-icons-c43422c
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.3-update-icons-c43422c
# or
yarn add @gravitee/ui-particles-angular@4.5.3-update-icons-c43422c
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.3-update-icons-2bc4755
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.3-update-icons-2bc4755
```

**Comment by audrey-tlm** [comment]
There are some labels that have been added to the SVG sprite, these texts should not be part of the export. I modified the Figma file so that texts are outside the 'Icons' frame, so that the texts are no longer embedded when you export icons.

**Comment by audrey-tlm** [comment]
There is two broken icons I need to fix before generating a new sprite: eye-empty, printer

**Comment by audrey-tlm** [comment]
> There is two broken icons I need to fix before generating a new sprite: eye-empty, printer

I updated these two icons, you can generate a new sprite

**Comment by gcusnieux** [comment]
> > There is two broken icons I need to fix before generating a new sprite: eye-empty, printer
> 
> I updated these two icons, you can generate a new sprite

@audrey-tlm done

**Comment by ThibaudAV** [comment]
some icone are strange no ? 
image

**Comment by ThibaudAV** [comment]
FYI you can have a preview here : 
image

https://6183b02d73381a003a3be1a6-tqthjglbmb.chromatic.com/?path=/story/components-icons--all

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.3-update-icons-247111c
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.3-update-icons-247111c
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.3-update-icons-247111c
# or
yarn add @gravitee/ui-particles-angular@4.5.3-update-icons-247111c
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.3-update-icons-93fab49
# or
yarn add @gravitee/ui-particles-angular@4.5.3-update-icons-93fab49
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.3-update-icons-93fab49
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.3-update-icons-93fab49
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.3-update-icons-b7fcaf8
# or
yarn add @gravitee/ui-particles-angular@4.5.3-update-icons-b7fcaf8
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.3-update-icons-b7fcaf8
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.3-update-icons-b7fcaf8
```

**Review by audrey-tlm — APPROVED** [review]

**Review by ThibaudAV — APPROVED** [review]
Je pense qu'il y a un petit pb sur le test qui check pas les icons en trop 🤔 

un `expect(icons).toEqual(all)` pourrais suffire 🤷‍♂️ 
ou une comparaison sur le nombre 

Sinon top c'est ✅

**Comment by gcusnieux** [comment]
> Je pense qu'il y a un petit pb sur le test qui check pas les icons en trop 🤔
> 
> un `expect(icons).toEqual(all)` pourrais suffire 🤷‍♂️ ou une comparaison sur le nombre
> 
> Sinon top c'est ✅

Oui mais comme ça ça permets d'avoir que le diff... et de le prendre pour mettre à jour la liste si nécessaire ;)

**Pull request merged**
