### PR TITLE
fix(gio-menu): resolve submenu position

### PR DESCRIPTION
**Pull request by gcusnieux**
**Issue**

https://graviteecommunity.atlassian.net/browse/APIM-393

**Description**

A small description of what you did in that PR.

**Additional context**

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-oqwesxfxqu.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.10.6-393-submenu-position-f790c66
# or
yarn add @gravitee/ui-policy-studio-angular@4.10.6-393-submenu-position-f790c66
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.10.6-393-submenu-position-f790c66
# or
yarn add @gravitee/ui-particles-angular@4.10.6-393-submenu-position-f790c66
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.10.6-393-submenu-position-2317b8a
# or
yarn add @gravitee/ui-particles-angular@4.10.6-393-submenu-position-2317b8a
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.10.6-393-submenu-position-2317b8a
# or
yarn add @gravitee/ui-policy-studio-angular@4.10.6-393-submenu-position-2317b8a
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.10.6-393-submenu-position-76ab0b4
# or
yarn add @gravitee/ui-policy-studio-angular@4.10.6-393-submenu-position-76ab0b4
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.10.6-393-submenu-position-76ab0b4
# or
yarn add @gravitee/ui-particles-angular@4.10.6-393-submenu-position-76ab0b4
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.10.6-393-submenu-position-272ca94
# or
yarn add @gravitee/ui-particles-angular@4.10.6-393-submenu-position-272ca94
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.10.6-393-submenu-position-272ca94
# or
yarn add @gravitee/ui-policy-studio-angular@4.10.6-393-submenu-position-272ca94
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.10.6-393-submenu-position-f9ea982
# or
yarn add @gravitee/ui-particles-angular@4.10.6-393-submenu-position-f9ea982
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.10.6-393-submenu-position-f9ea982
# or
yarn add @gravitee/ui-policy-studio-angular@4.10.6-393-submenu-position-f9ea982
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.10.6-393-submenu-position-1a6307a
# or
yarn add @gravitee/ui-policy-studio-angular@4.10.6-393-submenu-position-1a6307a
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.10.6-393-submenu-position-1a6307a
# or
yarn add @gravitee/ui-particles-angular@4.10.6-393-submenu-position-1a6307a
```

**Review by ThibaudAV — APPROVED** [review]

**Pull request merged**
