### PR TITLE
feat: add drag indicator icon

### PR DESCRIPTION
**Pull request by Okhelifi**
**Issue**

https://graviteecommunity.atlassian.net/browse/APIM-310

**Description**

Add drag indicator icon

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-kxdznmzytk.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.6.1-feat-add-drag-icon-2da5fdc
# or
yarn add @gravitee/ui-particles-angular@4.6.1-feat-add-drag-icon-2da5fdc
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.6.1-feat-add-drag-icon-6d1fd57
# or
yarn add @gravitee/ui-policy-studio-angular@4.6.1-feat-add-drag-icon-6d1fd57
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.6.1-feat-add-drag-icon-6d1fd57
# or
yarn add @gravitee/ui-particles-angular@4.6.1-feat-add-drag-icon-6d1fd57
```

**Review by ThibaudAV — APPROVED** [review]

**Pull request merged**
