### PR TITLE
chore: migrate to angular 13

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**

To allow more flexibility to apim console for migration of schema form

**Description**

Migrate to Angular 13

**Additional context**

---
#### 🧪&nbsp;&nbsp;Gravitee.io Automatic Prerelease
```
npm install @gravitee/ui-particles-angular@4.12.0-angular-13-7d3fa8b
```
```
yarn add @gravitee/ui-particles-angular@4.12.0-angular-13-7d3fa8b
```

---

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.12.0-angular-13-e54d0ff
# or
yarn add @gravitee/ui-policy-studio-angular@4.12.0-angular-13-e54d0ff
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.12.0-angular-13-e54d0ff
# or
yarn add @gravitee/ui-particles-angular@4.12.0-angular-13-e54d0ff
```

**Comment by gcusnieux** [comment]
Should we use another type than `chore` to increment the version?

**Comment by ThibaudAV** [comment]
Oops too much focus on the 1001 a bug 
I propose a BREAKING CHANGE to move on to the next major

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.12.0-angular-13-6004007
# or
yarn add @gravitee/ui-particles-angular@4.12.0-angular-13-6004007
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.12.0-angular-13-6004007
# or
yarn add @gravitee/ui-policy-studio-angular@4.12.0-angular-13-6004007
```

**Review by gcusnieux — APPROVED** [review]

**Pull request merged**
