### PR TITLE
feat: add Pendo module for analytics

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**

https://github.com/gravitee-io/issues/issues/7781

**Description**

Add Pendo Analytics Module

**Additional context**

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-agpmkffvao.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.4.0-pendo-97d55cb
# or
yarn add @gravitee/ui-particles-angular@3.4.0-pendo-97d55cb
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.4.0-pendo-ee2b405
# or
yarn add @gravitee/ui-particles-angular@3.4.0-pendo-ee2b405
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.4.0-pendo-ee2b405
# or
yarn add @gravitee/ui-policy-studio-angular@3.4.0-pendo-ee2b405
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.4.0-pendo-c99eedf
# or
yarn add @gravitee/ui-policy-studio-angular@3.4.0-pendo-c99eedf
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.4.0-pendo-c99eedf
# or
yarn add @gravitee/ui-particles-angular@3.4.0-pendo-c99eedf
```

**Review by gaetanmaisse — APPROVED** [review]

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.4.0-pendo-8c8abff
# or
yarn add @gravitee/ui-particles-angular@3.4.0-pendo-8c8abff
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.4.0-pendo-8c8abff
# or
yarn add @gravitee/ui-policy-studio-angular@3.4.0-pendo-8c8abff
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.4.0-pendo-5edd916
# or
yarn add @gravitee/ui-particles-angular@3.4.0-pendo-5edd916
```

**Pull request merged**
