### PR TITLE
feat: add avatar component

### PR DESCRIPTION
**Pull request by loriepisicchio**
**Issue**

N.A.

**Description**

Add avatar component (will me moved out of APIM code when merged)

**Screenshot**

Screenshot 2022-11-29 at 10 32 06

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-uvrjepixon.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.9.0-add-avatar-component-578f3a0
# or
yarn add @gravitee/ui-particles-angular@4.9.0-add-avatar-component-578f3a0
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.9.0-add-avatar-component-578f3a0
# or
yarn add @gravitee/ui-policy-studio-angular@4.9.0-add-avatar-component-578f3a0
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.9.0-add-avatar-component-11d9b4e
# or
yarn add @gravitee/ui-policy-studio-angular@4.9.0-add-avatar-component-11d9b4e
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.9.0-add-avatar-component-c8837e0
# or
yarn add @gravitee/ui-policy-studio-angular@4.9.0-add-avatar-component-c8837e0
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.9.0-add-avatar-component-c8837e0
# or
yarn add @gravitee/ui-particles-angular@4.9.0-add-avatar-component-c8837e0
```

**Review by gcusnieux — APPROVED** [review]

**Review by ThibaudAV — APPROVED** [review]

**Pull request merged**
