### PR TITLE
Improve QA with eslint rules & stylelint

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**
Improve QA

**Description**
- add eslint order rules 
- add styelint

**Additional context**

 bad branche name 🙈 

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-oqqkhpiuzq.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@2.7.0-override-mat-tab-label-81c2492
# or
yarn add @gravitee/ui-policy-studio-angular@2.7.0-override-mat-tab-label-81c2492
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@2.7.0-override-mat-tab-label-81c2492
# or
yarn add @gravitee/ui-particles-angular@2.7.0-override-mat-tab-label-81c2492
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@2.7.0-override-mat-tab-label-ba01d2b
# or
yarn add @gravitee/ui-particles-angular@2.7.0-override-mat-tab-label-ba01d2b
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@2.7.0-override-mat-tab-label-ba01d2b
# or
yarn add @gravitee/ui-policy-studio-angular@2.7.0-override-mat-tab-label-ba01d2b
```

**Review by gaetanmaisse — APPROVED** [review]

**Review by Okhelifi — APPROVED** [review]

**Comment by ThibaudAV** [comment]
fixed 🏩  chromatic

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@2.7.0-override-mat-tab-label-2019ea6
# or
yarn add @gravitee/ui-particles-angular@2.7.0-override-mat-tab-label-2019ea6
```

**Pull request merged**
