### PR TITLE
feat(menu): implement keyboard nav 

### PR DESCRIPTION
**Pull request by gcusnieux**
APIM-226

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-ilyierayhf.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.3.0-menu-keyboard-22f778c
# or
yarn add @gravitee/ui-policy-studio-angular@4.3.0-menu-keyboard-22f778c
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.3.0-menu-keyboard-22f778c
# or
yarn add @gravitee/ui-particles-angular@4.3.0-menu-keyboard-22f778c
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.3.0-menu-keyboard-2aecd65
# or
yarn add @gravitee/ui-policy-studio-angular@4.3.0-menu-keyboard-2aecd65
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.3.0-menu-keyboard-2aecd65
# or
yarn add @gravitee/ui-particles-angular@4.3.0-menu-keyboard-2aecd65
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.3.0-menu-keyboard-7a15613
# or
yarn add @gravitee/ui-particles-angular@4.3.0-menu-keyboard-7a15613
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.3.0-menu-keyboard-7a15613
# or
yarn add @gravitee/ui-policy-studio-angular@4.3.0-menu-keyboard-7a15613
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.3.0-menu-keyboard-6f2b4b5
# or
yarn add @gravitee/ui-policy-studio-angular@4.3.0-menu-keyboard-6f2b4b5
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.3.0-menu-keyboard-6f2b4b5
# or
yarn add @gravitee/ui-particles-angular@4.3.0-menu-keyboard-6f2b4b5
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.3.0-menu-keyboard-327f3cd
# or
yarn add @gravitee/ui-particles-angular@4.3.0-menu-keyboard-327f3cd
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.3.0-menu-keyboard-327f3cd
# or
yarn add @gravitee/ui-policy-studio-angular@4.3.0-menu-keyboard-327f3cd
```

**Review by phiz71 — APPROVED** [review]

**Review by ThibaudAV — APPROVED** [review]

**Pull request merged**
