### PR TITLE
docs: add readme for button usage

### PR DESCRIPTION
**Pull request by audrey-tlm**
I added some description for the button usage

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-dkmwlkcepm.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.3-add-button-readme-dfc345e
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.3-add-button-readme-dfc345e
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.3-add-button-readme-dfc345e
# or
yarn add @gravitee/ui-particles-angular@4.5.3-add-button-readme-dfc345e
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.3-add-button-readme-c4f902a
# or
yarn add @gravitee/ui-particles-angular@4.5.3-add-button-readme-c4f902a
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.8.1-add-button-readme-98e634e
# or
yarn add @gravitee/ui-policy-studio-angular@4.8.1-add-button-readme-98e634e
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.8.1-add-button-readme-98e634e
# or
yarn add @gravitee/ui-particles-angular@4.8.1-add-button-readme-98e634e
```

**Review by gcusnieux — APPROVED** [review]

**Pull request merged**
