### PR TITLE
feat(gio-save-bar): add possibility to override default css

### PR DESCRIPTION
**Pull request by gcusnieux**
---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-oqhiwxlzpq.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@2.3.0-gio-save-bar-override-margin-69666a0
# or
yarn add @gravitee/ui-policy-studio-angular@2.3.0-gio-save-bar-override-margin-69666a0
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@2.3.0-gio-save-bar-override-margin-69666a0
# or
yarn add @gravitee/ui-particles-angular@2.3.0-gio-save-bar-override-margin-69666a0
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@2.3.0-gio-save-bar-override-margin-32475b1
# or
yarn add @gravitee/ui-particles-angular@2.3.0-gio-save-bar-override-margin-32475b1
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@2.3.0-gio-save-bar-override-margin-32475b1
# or
yarn add @gravitee/ui-policy-studio-angular@2.3.0-gio-save-bar-override-margin-32475b1
```

**Review by ThibaudAV — APPROVED** [review]
The bar is a bit bigger. it's better 

Tested with apim (policy studio and organisation setting) 🆗

**Pull request merged**
