### PR TITLE
feat: update mat palette colors

### PR DESCRIPTION
**Pull request by Okhelifi**
**Description**

Update mat palette colors.

Here is the link of the colors reference https://www.figma.com/file/XvLO9G5fPRIrfyhLjPg6a2/Gravitee_Lib_elemZ?node-id=1493%3A1143

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-wsnlzqmgbe.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@2.9.0-feat-update-palettes-debe298
# or
yarn add @gravitee/ui-particles-angular@2.9.0-feat-update-palettes-debe298
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@2.9.0-feat-update-palettes-2287c18
# or
yarn add @gravitee/ui-particles-angular@2.9.0-feat-update-palettes-2287c18
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@2.9.0-feat-update-palettes-2287c18
# or
yarn add @gravitee/ui-policy-studio-angular@2.9.0-feat-update-palettes-2287c18
```

**Comment by gaetanmaisse** [comment]
Maybe it could make sense to ask Poppy, @audrey-tlm or Greg to validate the UI Tests of Chromatic. WDYT?

**Comment by Okhelifi** [comment]
> Maybe it could make sense to ask Poppy, @audrey-tlm or Greg to validate the UI Tests of Chromatic. WDYT?

Yes sure let's do it

**Review by ThibaudAV — COMMENTED** [review]
what do you think about keeping a display without having a scroll ? 

image
I have a 2k screen 😁 

Same for the Readme part, it's a lot of space lost for not much I think. 

If you want I can do it

**Comment by audrey-tlm** [comment]
I think we can keep this display, to have the same view between Storybook and Figma to be able to navigate more easily

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@2.11.0-feat-update-palettes-902c281
# or
yarn add @gravitee/ui-particles-angular@2.11.0-feat-update-palettes-902c281
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@2.11.0-feat-update-palettes-dc78616
# or
yarn add @gravitee/ui-policy-studio-angular@2.11.0-feat-update-palettes-dc78616
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@2.11.0-feat-update-palettes-dc78616
# or
yarn add @gravitee/ui-particles-angular@2.11.0-feat-update-palettes-dc78616
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@2.11.0-feat-update-palettes-c66721f
# or
yarn add @gravitee/ui-policy-studio-angular@2.11.0-feat-update-palettes-c66721f
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@2.11.0-feat-update-palettes-c66721f
# or
yarn add @gravitee/ui-particles-angular@2.11.0-feat-update-palettes-c66721f
```

**Pull request merged**
