### PR TITLE
feat: improve banner to have optional body

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**

Improve banner to have optional body

**Description**
image

**Additional context**

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-fulwewnzke.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.2.0-banner-57f8faa
# or
yarn add @gravitee/ui-particles-angular@4.2.0-banner-57f8faa
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.2.0-banner-57f8faa
# or
yarn add @gravitee/ui-policy-studio-angular@4.2.0-banner-57f8faa
```

**Review by gcusnieux — APPROVED** [review]

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.2.0-banner-82c949e
# or
yarn add @gravitee/ui-policy-studio-angular@4.2.0-banner-82c949e
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.2.0-banner-82c949e
# or
yarn add @gravitee/ui-particles-angular@4.2.0-banner-82c949e
```

**Pull request merged**
