### PR TITLE
fix(menu): set z-index only when submenu overlay mode

### PR DESCRIPTION
**Pull request by gcusnieux**
**Issue**

APIM-271

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-nvefnjbajg.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.0-fix-feedback-6c7c871
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.0-fix-feedback-6c7c871
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.0-fix-feedback-6c7c871
# or
yarn add @gravitee/ui-particles-angular@4.5.0-fix-feedback-6c7c871
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.0-fix-feedback-8fa4a3a
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.0-fix-feedback-8fa4a3a
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.0-fix-feedback-8fa4a3a
# or
yarn add @gravitee/ui-particles-angular@4.5.0-fix-feedback-8fa4a3a
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.0-fix-feedback-5e00285
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.0-fix-feedback-5e00285
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.0-fix-feedback-5e00285
# or
yarn add @gravitee/ui-particles-angular@4.5.0-fix-feedback-5e00285
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.1-fix-feedback-89866c4
# or
yarn add @gravitee/ui-particles-angular@4.5.1-fix-feedback-89866c4
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.1-fix-feedback-89866c4
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.1-fix-feedback-89866c4
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.5.1-fix-feedback-da7e8ec
# or
yarn add @gravitee/ui-policy-studio-angular@4.5.1-fix-feedback-da7e8ec
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.1-fix-feedback-da7e8ec
# or
yarn add @gravitee/ui-particles-angular@4.5.1-fix-feedback-da7e8ec
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.5.1-fix-feedback-38f5f0a
# or
yarn add @gravitee/ui-particles-angular@4.5.1-fix-feedback-38f5f0a
```

**Review by ThibaudAV — APPROVED** [review]

**Pull request merged**
