### PR TITLE
Banner: Remove extra info text in info banner

### PR DESCRIPTION
**Pull request by gaetanmaisse**
**Issue**

NA

**Description**

Remove extra info text in info banner

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-zzzhsygdlx.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.3.0-fix-info-banner-aa0e3c9
# or
yarn add @gravitee/ui-policy-studio-angular@3.3.0-fix-info-banner-aa0e3c9
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.3.0-fix-info-banner-aa0e3c9
# or
yarn add @gravitee/ui-particles-angular@3.3.0-fix-info-banner-aa0e3c9
```

**Review by ThibaudAV — APPROVED** [review]

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.3.0-fix-info-banner-f643236
# or
yarn add @gravitee/ui-policy-studio-angular@3.3.0-fix-info-banner-f643236
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.3.0-fix-info-banner-f643236
# or
yarn add @gravitee/ui-particles-angular@3.3.0-fix-info-banner-f643236
```

**Pull request merged**
