### PR TITLE
feat: add palettes for the new design system colors

### PR DESCRIPTION
**Pull request by loriepisicchio**
**Description**

Add new color palettes from the new design system Perseverance

**Screenshot**
image

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-lzgcyouurj.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.5.1-new-color-palettes-90e5e0a
# or
yarn add @gravitee/ui-particles-angular@3.5.1-new-color-palettes-90e5e0a
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.5.1-new-color-palettes-90e5e0a
# or
yarn add @gravitee/ui-policy-studio-angular@3.5.1-new-color-palettes-90e5e0a
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.5.1-new-color-palettes-6708bd9
# or
yarn add @gravitee/ui-policy-studio-angular@3.5.1-new-color-palettes-6708bd9
```

**Review by jgiovaresco — APPROVED** [review]

**Review by gaetanmaisse — CHANGES_REQUESTED** [review]
If we are moving to Perseverance colors we need to clean the other ones to not have a catch-all _(fourre-tout)_ library

**Pull request closed without merging**
