### PR TITLE
fix(gio-save-bar): deal with timer in submit handler

### PR DESCRIPTION
**Pull request by gcusnieux**
**Issue**

https://github.com/gravitee-io/issues/issues/XXXXX

**Description**

A small description of what you did in that PR.

**Additional context**

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-trpxrkftup.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.10.3-fix-save-bar-harness-e4ff928
# or
yarn add @gravitee/ui-particles-angular@4.10.3-fix-save-bar-harness-e4ff928
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.10.3-fix-save-bar-harness-8cb3d09
# or
yarn add @gravitee/ui-particles-angular@4.10.3-fix-save-bar-harness-8cb3d09
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.10.3-fix-save-bar-harness-8cb3d09
# or
yarn add @gravitee/ui-policy-studio-angular@4.10.3-fix-save-bar-harness-8cb3d09
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.10.3-fix-save-bar-harness-c82f8ab
# or
yarn add @gravitee/ui-policy-studio-angular@4.10.3-fix-save-bar-harness-c82f8ab
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.10.3-fix-save-bar-harness-c82f8ab
# or
yarn add @gravitee/ui-particles-angular@4.10.3-fix-save-bar-harness-c82f8ab
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.10.3-fix-save-bar-harness-de4fe7e
# or
yarn add @gravitee/ui-particles-angular@4.10.3-fix-save-bar-harness-de4fe7e
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.10.3-fix-save-bar-harness-de4fe7e
# or
yarn add @gravitee/ui-policy-studio-angular@4.10.3-fix-save-bar-harness-de4fe7e
```

**Review by ThibaudAV — APPROVED** [review]

**Pull request merged**
