### PR TITLE
Update CircleCI context used in config.yml

### PR DESCRIPTION
**Pull request by gaetanmaisse**
**Issue**

NA

**Description**

Remove usage of `gravitee-qa` as env variables are already contained in `cicd-orchestrator`

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-smahkoumos.chromatic.com)

### CODE REVIEW

**Review by ThibaudAV — APPROVED** [review]

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.12.0-update-circleci-context-a493d9f
# or
yarn add @gravitee/ui-policy-studio-angular@4.12.0-update-circleci-context-a493d9f
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.12.0-update-circleci-context-a493d9f
# or
yarn add @gravitee/ui-particles-angular@4.12.0-update-circleci-context-a493d9f
```

**Pull request merged**
