### PR TITLE
Remove unused icons & add color customization

### PR DESCRIPTION
**Pull request by audrey-tlm**
**Issue**

NA

**Description**

- I removed unused icons from the sprite
- I added `currentColor` property to each path and group inside SVG to allow the color customization

**Additional context**

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-hevltahxqr.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@2.2.0-update-icons-d164234
# or
yarn add @gravitee/ui-particles-angular@2.2.0-update-icons-d164234
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@2.2.0-update-icons-d164234
# or
yarn add @gravitee/ui-policy-studio-angular@2.2.0-update-icons-d164234
```

**Review by gaetanmaisse — APPROVED** [review]
✅  LGTM. As said in mp it would be great to update the branch with the latest changes of `main`, to see the icons colored in the Badge story :)

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@2.6.0-update-icons-60faece
# or
yarn add @gravitee/ui-particles-angular@2.6.0-update-icons-60faece
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@2.6.0-update-icons-60faece
# or
yarn add @gravitee/ui-policy-studio-angular@2.6.0-update-icons-60faece
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@2.9.0-update-icons-e6dd5bd
# or
yarn add @gravitee/ui-particles-angular@2.9.0-update-icons-e6dd5bd
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@2.9.0-update-icons-e6dd5bd
# or
yarn add @gravitee/ui-policy-studio-angular@2.9.0-update-icons-e6dd5bd
```

**Pull request merged**
