### PR TITLE
feat: create component gio-form-radio-toggle-button

### PR DESCRIPTION
**Pull request by loriepisicchio**
**Issue**

New component required for https://gravitee.atlassian.net/browse/APIM-2791

**Description**

Create a new radio button group component with custom style 

Screenshot 2023-10-12 at 13 17 09

Inspired by Figma component https://www.figma.com/file/fMXSfpGCQGVq39MgehrD6f/Documentation?type=design&node-id=1322-10193&mode=design&t=GAxj33HdLlSDdEjM-4

NB: we can not remove the "circle" icon from the radio button without doing some dark and unmaintainable CSS code using `ng::deep` so I suggest we keep it this way. Would require @audrey-tlm approval on that.

---
#### 🧪&nbsp;&nbsp;Gravitee.io Automatic Prerelease @gravitee/ui-particles-angular
```
npm install @gravitee/ui-particles-angular@7.35.0-create-custom-radio-toggle-15af9d5
```
```
yarn add @gravitee/ui-particles-angular@7.35.0-create-custom-radio-toggle-15af9d5
```

---
#### 🧪&nbsp;&nbsp;Gravitee.io Automatic Prerelease @gravitee/ui-policy-studio-angular
```
npm install @gravitee/ui-policy-studio-angular@7.35.0-create-custom-radio-toggle-15af9d5
```
```
yarn add @gravitee/ui-policy-studio-angular@7.35.0-create-custom-radio-toggle-15af9d5
```

---

### CODE REVIEW

**Review by jourdiw — APPROVED** [review]
LGTM

**Review by ThibaudAV — APPROVED** [review]
tooooogle 😁 

I'm just wondering if we couldn't remove the !important with more precise class name. but 🤷‍♂️ .

**Comment by loriepisicchio** [comment]
@ThibaudAV they were actually not necessary so I removed them

**Pull request merged**
