### PR TITLE
feat: add confirm and validate dialog component

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**

https://github.com/gravitee-io/issues/issues/XXXXX

**Description**

image
image
image

**Additional context**

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-beydhyymzl.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.11.1-confirm-and-validate-dialog-79e0c90
# or
yarn add @gravitee/ui-policy-studio-angular@3.11.1-confirm-and-validate-dialog-79e0c90
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.11.1-confirm-and-validate-dialog-79e0c90
# or
yarn add @gravitee/ui-particles-angular@3.11.1-confirm-and-validate-dialog-79e0c90
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.11.1-confirm-and-validate-dialog-b3a6e3b
# or
yarn add @gravitee/ui-policy-studio-angular@3.11.1-confirm-and-validate-dialog-b3a6e3b
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.11.1-confirm-and-validate-dialog-b3a6e3b
# or
yarn add @gravitee/ui-particles-angular@3.11.1-confirm-and-validate-dialog-b3a6e3b
```

**Review by Okhelifi — APPROVED** [review]

**Pull request merged**
