### PR TITLE
feat: create release on npm registry

### PR DESCRIPTION
**Pull request by ThibaudAV**
**Issue**
na

**Description**

add feat commit to create release on npm registry

**Additional context**

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@1.1.1-relase-8be9b08
# or
yarn add @gravitee/ui-particles-angular@1.1.1-relase-8be9b08
```

**Review by gaetanmaisse — APPROVED** [review]

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-hajptpximg.chromatic.com)

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

A prerelease version of this package has been published! 🚀

To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@1.3.1-relase-ed9462d
# or
yarn add @gravitee/ui-particles-angular@1.3.1-relase-ed9462d
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**

📚 View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-bvtfiyklyi.chromatic.com)

**Pull request merged**
