### PR TITLE
feat(CI): get chromatic token from keeper

### PR DESCRIPTION
**Pull request by sebdevaux**
Security fix

---
#### 🧪&nbsp;&nbsp;Gravitee.io Automatic Prerelease
```
npm install @gravitee/ui-policy-studio-angular@5.1.0-devops-50-cci-use-ksm-1db3f0c
```
```
yarn add @gravitee/ui-policy-studio-angular@5.1.0-devops-50-cci-use-ksm-1db3f0c
```

---

### CODE REVIEW

**Review by gaetanmaisse — APPROVED** [review]

**Review by ThibaudAV — APPROVED** [review]

**Comment by gaetanmaisse** [comment]
Let's see if Chromatic is still running with that 🙈

**Comment by gaetanmaisse** [comment]
And it's 🚀

**Comment by gaetanmaisse** [comment]
Looks good now
image

**Pull request merged**
