### PR TITLE
fix(gio-save-bar): prevent multiple submit

### PR DESCRIPTION
**Pull request by gcusnieux**
**Issue**

https://github.com/gravitee-io/issues/issues/XXXXX

**Description**

A small description of what you did in that PR.

**Additional context**

---
📚&nbsp;&nbsp;View the storybook of this branch [here](https://6183b02d73381a003a3be1a6-avubnghtij.chromatic.com)

### CODE REVIEW

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@4.10.0-improve-save-bar-with-disabled-aa115ae
# or
yarn add @gravitee/ui-policy-studio-angular@4.10.0-improve-save-bar-with-disabled-aa115ae
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.10.0-improve-save-bar-with-disabled-aa115ae
# or
yarn add @gravitee/ui-particles-angular@4.10.0-improve-save-bar-with-disabled-aa115ae
```

**Comment by graviteeio** [comment]
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@4.10.0-improve-save-bar-with-disabled-5d44460
# or
yarn add @gravitee/ui-particles-angular@4.10.0-improve-save-bar-with-disabled-5d44460
```

**Review by gaetanmaisse — APPROVED** [review]
Looks good, do we have a way to add a unit test for that?

**Pull request merged**
